spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.digitaltwin.platform: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG

app:
  cors:
    allowed-origins: http://localhost:5173,http://127.0.0.1:5173

springdoc:
  swagger-ui:
    path: /swagger-ui.html
